"""W3.3 — does our ESTIMATE reproduce the real ESTIMATE?

`src/bulk/purity.py` reimplements a GPL-2 R package because R does not run
here. A reimplementation that quietly differs from the canonical tool is worse
than no tool at all, so the load-bearing test in this file is
:func:`test_reproduces_the_packages_own_reference_output` — the ESTIMATE
package ships ``sample_input.gct`` together with the ``sample_estimate.gct`` it
produces from it, and we assert we match those numbers.

If that test passes, this is ESTIMATE. If it fails, nothing else here matters.

The fixture is downloaded rather than committed: it is someone else's GPL-2
material and vendoring it raises a licensing question for no benefit. Tests
that need it skip when it is absent, so CI stays green offline.
"""

from __future__ import annotations

import io
import tarfile

import numpy as np
import pandas as pd
import pytest

from src.bulk.purity import (
    AFFY_PURITY_INTERCEPT,
    AFFY_PURITY_SLOPE,
    PurityError,
    affymetrix_purity,
    agreement,
    assemble_purity_table,
    estimate_scores,
    filter_common_genes,
    load_common_genes,
    load_signatures,
    to_symbol_matrix,
)
from src.common.paths import RAW_DIR

ESTIMATE_TARBALL = RAW_DIR / "estimate" / "estimate_1.0.13.tar.gz"
needs_package = pytest.mark.skipif(
    not ESTIMATE_TARBALL.exists(),
    reason="ESTIMATE source not downloaded; run `python -m src.bulk.run_purity fetch`",
)


def _read_gct(text: str) -> pd.DataFrame:
    """GCT: two header lines, then Name/Description/samples..."""
    df = pd.read_csv(io.StringIO(text), sep="\t", skiprows=2, index_col=0)
    return df.drop(columns=[df.columns[0]])


def _member(suffix: str) -> str:
    with tarfile.open(ESTIMATE_TARBALL, "r:gz") as tf:
        for m in tf.getmembers():
            if m.name.endswith(suffix):
                return tf.extractfile(m).read().decode("utf-8")
    raise AssertionError(f"{suffix} missing")


# ---------------------------------------------------------------------------
# THE test
# ---------------------------------------------------------------------------


@needs_package
def test_reproduces_the_packages_own_reference_output():
    """Our scores must equal the ones estimateScore.R produced for its own example.

    sample_input.gct (17,256 genes x 10 samples) -> sample_estimate.gct.
    Tolerance is 1e-6 relative: this is a port, not an approximation.
    """
    raw = _read_gct(_member("inst/extdata/sample_input.gct"))
    reference = _read_gct(_member("inst/extdata/sample_estimate.gct"))
    signatures = load_signatures(ESTIMATE_TARBALL)

    # The reference was produced AFTER filterCommonGenes; scoring the raw
    # 17,256-gene matrix divides ranks by the wrong gene count.
    expression = filter_common_genes(raw, load_common_genes(ESTIMATE_TARBALL))
    assert len(expression) < len(raw)

    ours = estimate_scores(expression, signatures)

    np.testing.assert_allclose(
        ours["StromalScore"].to_numpy(),
        reference.loc["Stromal141_UP"].to_numpy(dtype=float),
        rtol=1e-6,
        err_msg="stromal score diverges from the reference implementation",
    )
    np.testing.assert_allclose(
        ours["ImmuneScore"].to_numpy(),
        reference.loc["Immune141_UP"].to_numpy(dtype=float),
        rtol=1e-6,
        err_msg="immune score diverges from the reference implementation",
    )
    np.testing.assert_allclose(
        ours["ESTIMATEScore"].to_numpy(),
        reference.loc["ESTIMATE"].to_numpy(dtype=float),
        rtol=1e-6,
    )


@needs_package
def test_the_shipped_purity_example_is_stale_relative_to_the_source():
    """The package's own sample_purity.gct does NOT match its own code.

    Both fixtures carry an identical ESTIMATE row, so purity should be a
    deterministic function of a number we already reproduce exactly. It is not.
    Solving cos-inverse back through the fixture gives

        intercept 0.6036365441, slope 0.0001506451

    against the ``estimateScore.R`` v1.0.13 source values

        intercept 0.6049872018, slope 0.0001467884

    with a linear-fit residual of 8e-16 — machine precision. So the shipped
    example was generated by an earlier version of the conversion and never
    regenerated. **We follow the source, not the stale example**, and the
    remaining disagreement is at most ~0.015 in purity units.

    This test pins the discrepancy rather than hiding it behind a loose
    tolerance. If a future ESTIMATE release regenerates the example, this test
    fails and someone re-reads the constants — which is the correct outcome.
    """
    purity_gct = _read_gct(_member("inst/extdata/sample_purity.gct"))
    expression = filter_common_genes(
        _read_gct(_member("inst/extdata/sample_input.gct")),
        load_common_genes(ESTIMATE_TARBALL),
    )
    signatures = load_signatures(ESTIMATE_TARBALL)
    scores = estimate_scores(expression, signatures)["ESTIMATEScore"]

    reference = purity_gct.loc["ESTIMATE-predicted tumor purity"].to_numpy(dtype=float)

    # We match the source formula exactly.
    ours = affymetrix_purity(scores).to_numpy(dtype=float)
    np.testing.assert_allclose(
        ours, np.cos(AFFY_PURITY_INTERCEPT + AFFY_PURITY_SLOPE * scores.to_numpy()), rtol=1e-12
    )

    # And the fixture is exactly reproducible with the older constants, which is
    # what proves the machinery is right and only the constants moved.
    stale = np.cos(0.6036365441 + 0.0001506451 * scores.to_numpy())
    np.testing.assert_allclose(stale, reference, atol=1e-9)

    # The practical size of the disagreement, stated rather than assumed.
    assert np.abs(ours - reference).max() < 0.02


@needs_package
def test_the_signatures_are_the_expected_shape():
    sigs = load_signatures(ESTIMATE_TARBALL)
    assert len(sigs["StromalSignature"]) == 141
    assert len(sigs["ImmuneSignature"]) == 141
    assert "DCN" in sigs["StromalSignature"]
    assert "LCP2" in sigs["ImmuneSignature"]


@needs_package
def test_common_gene_list_is_the_expected_size():
    assert len(set(load_common_genes(ESTIMATE_TARBALL))) == 10412


# ---------------------------------------------------------------------------
# Properties that hold without the package
# ---------------------------------------------------------------------------


def _toy(n_genes=400, n_samples=6, seed=0):
    rng = np.random.default_rng(seed)
    genes = [f"G{i}" for i in range(n_genes)]
    return pd.DataFrame(
        rng.lognormal(3, 1, (n_genes, n_samples)),
        index=genes,
        columns=[f"S{j}" for j in range(n_samples)],
    )


def _toy_signatures(expr):
    genes = list(expr.index)
    return {"StromalSignature": genes[:50], "ImmuneSignature": genes[50:100]}


def test_scale_invariance_tpm_and_log_agree_exactly():
    """The first step is a per-sample rank, so any monotone transform gives the
    same answer. Worth pinning: it means W3.3 is immune to the TPM/log2-CPM
    mix-up that the rest of the pipeline asserts against."""
    expr = _toy()
    sigs = _toy_signatures(expr)
    linear = estimate_scores(expr, sigs)
    logged = estimate_scores(np.log2(expr + 1), sigs)
    pd.testing.assert_frame_equal(linear, logged)


def test_stromal_signal_raises_the_stromal_score():
    """A positive control. Inflate the stromal genes and the score must move."""
    expr = _toy()
    sigs = _toy_signatures(expr)
    base = estimate_scores(expr, sigs)
    spiked = expr.copy()
    spiked.loc[sigs["StromalSignature"], "S0"] *= 50
    after = estimate_scores(spiked, sigs)
    assert after.loc["S0", "StromalScore"] > base.loc["S0", "StromalScore"]
    assert after.loc["S1", "StromalScore"] == pytest.approx(base.loc["S1", "StromalScore"])


def test_estimate_score_is_the_sum_of_the_two():
    scores = estimate_scores(_toy(), _toy_signatures(_toy()))
    np.testing.assert_allclose(
        scores["ESTIMATEScore"], scores["StromalScore"] + scores["ImmuneScore"]
    )


def test_no_purity_column_is_emitted_by_default():
    """The purity conversion is Affymetrix-only in the original. It has to be
    asked for explicitly, and it is not called 'purity'."""
    scores = estimate_scores(_toy(), _toy_signatures(_toy()))
    assert "TumorPurity" not in scores.columns
    assert not any("purity" in c.lower() for c in scores.columns)


def test_affy_purity_matches_the_published_formula():
    s = pd.Series([0.0, 1000.0, -2000.0])
    expected = np.cos(AFFY_PURITY_INTERCEPT + AFFY_PURITY_SLOPE * s)
    np.testing.assert_allclose(affymetrix_purity(s).to_numpy(), expected.to_numpy())


def test_affy_purity_nulls_out_of_range_values():
    """estimateScore.R sets negative purities to NA rather than clipping."""
    huge = pd.Series([50000.0])
    assert affymetrix_purity(huge).isna().all()


def test_empty_matrix_is_refused():
    with pytest.raises(PurityError, match="empty"):
        estimate_scores(pd.DataFrame(), {"StromalSignature": [], "ImmuneSignature": []})


def test_signature_with_no_overlap_is_refused():
    expr = _toy()
    with pytest.raises(PurityError, match="no genes from"):
        estimate_scores(
            expr, {"StromalSignature": ["NOPE"], "ImmuneSignature": ["ALSO_NOPE"]}
        )


# ---------------------------------------------------------------------------
# Symbol mapping and the output contract
# ---------------------------------------------------------------------------


def test_duplicate_symbols_collapse_to_the_dominant_transcript():
    expr = pd.DataFrame(
        {"E1": [100.0, 120.0], "E2": [1.0, 2.0], "E3": [7.0, 9.0]},
        index=["S0", "S1"],
    )
    gene_map = pd.DataFrame(
        {"ensembl_id": ["E1", "E2", "E3"], "gene_symbol": ["AAA", "AAA", "BBB"]}
    )
    out, counts = to_symbol_matrix(expr, gene_map, ["AAA", "BBB"])
    assert list(out.index) == ["AAA", "BBB"]
    assert out.loc["AAA", "S0"] == 100.0  # E1 wins, E2 dropped — not summed to 101
    assert counts["unique_symbols"] == 2


def test_symbol_mapping_reports_loss_at_each_step():
    expr = pd.DataFrame({"E1": [1.0], "E_unmapped": [2.0]}, index=["S0"])
    gene_map = pd.DataFrame({"ensembl_id": ["E1"], "gene_symbol": ["AAA"]})
    _, counts = to_symbol_matrix(expr, gene_map, ["AAA", "ZZZ"])
    assert counts["ensembl_in_matrix"] == 2
    assert counts["mapped_to_a_symbol"] == 1
    assert counts["in_estimate_common_genes"] == 1
    assert counts["common_genes_total"] == 2


def _manifest(barcodes):
    return pd.DataFrame(
        {
            "barcode": barcodes,
            "patient_id": [b[:12] for b in barcodes],
            "project": ["TCGA-COAD"] * len(barcodes),
            "sample_type": ["01"] * len(barcodes),
            "sample_type_name": ["primary_tumour"] * len(barcodes),
        }
    ).set_index("barcode")


def test_the_two_methods_are_never_coalesced():
    """The brief: 'do not silently coalesce the two'. One row per (sample,
    method), so ABSOLUTE's coverage gap stays visible instead of being
    backfilled with an expression-derived number."""
    barcodes = ["TCGA-AA-0000-01A-01R-1410-07", "TCGA-AA-0001-01A-01R-1410-07"]
    scores = pd.DataFrame(
        {"StromalScore": [10.0, 20.0], "ImmuneScore": [5.0, 6.0], "ESTIMATEScore": [15.0, 26.0]},
        index=pd.Index(barcodes, name="barcode"),
    )
    # ABSOLUTE is keyed at sample level — it is called from a DNA aliquot that
    # never shares a barcode with our RNA aliquot.
    absolute = pd.DataFrame(
        {
            "sample_key": ["TCGA-AA-0000-01A"],
            "cancer_type": ["COAD"],
            "aran_absolute": [0.7],
            "aran_estimate": [0.8],
            "aran_cpe": [0.75],
        }
    )
    table = assemble_purity_table(scores, absolute, manifest=_manifest(barcodes))

    assert set(table["method"]) == {"estimate_affy_extrapolated", "absolute", "aran_cpe"}
    assert len(table) == 4  # two ESTIMATE rows, one ABSOLUTE, one CPE
    matched = table[table["barcode"] == barcodes[0]]
    assert set(matched["method"]) == {"estimate_affy_extrapolated", "absolute", "aran_cpe"}
    # The unmatched sample keeps its ESTIMATE row and gains nothing else — the
    # coverage gap stays visible rather than being backfilled.
    assert table[table["barcode"] == barcodes[1]]["method"].tolist() == [
        "estimate_affy_extrapolated"
    ]
    assert table.loc[table["method"] == "absolute", "expression_derived"].eq(False).all()
    assert table.loc[
        table["method"] == "estimate_affy_extrapolated", "expression_derived"
    ].all()


def test_sample_key_bridges_the_dna_rna_aliquot_gap():
    from src.bulk.purity import sample_key

    assert sample_key("TCGA-A6-2670-01A-01R-1410-07") == "TCGA-A6-2670-01A"
    # A DNA aliquot of the same sample maps to the same key. That is the point.
    assert sample_key("TCGA-A6-2670-01A-11D-A29H-01") == "TCGA-A6-2670-01A"


def test_agreement_reports_coverage_even_with_no_absolute():
    scores = pd.DataFrame(
        {"StromalScore": [10.0], "ImmuneScore": [5.0], "ESTIMATEScore": [15.0]},
        index=pd.Index(["TCGA-AA-0000-01A"], name="barcode"),
    )
    table = assemble_purity_table(scores, None, manifest=_manifest(list(scores.index)))
    stats = agreement(table)
    assert stats["n_absolute"] == 0
    assert stats["absolute_coverage"] == 0.0
    assert "pearson_r" not in stats
