"""Forcing inputs for the audit reproduction index.

The index must not silently drop a deliverable, must not let a blocked
deliverable read as done, and must record paths a fresh checkout can resolve.
"""

from __future__ import annotations

import json

import pandas as pd

from src.common.paths import RESULTS_DIR
from src.reference.reproduction import (
    DELIVERABLES,
    build_manifest,
    unavailable_deliverables,
)
from src.reference.table_resolution import newest_by_time


def _write_result(results_dir, dirname, table, **meta):
    d = results_dir / dirname
    d.mkdir(parents=True)
    pd.DataFrame({"a": [1, 2]}).to_parquet(d / f"{table}.parquet")
    base = {"utc_timestamp": "2026-01-01T00:00:00+00:00", "git_sha": "abc1234",
            "git_dirty": False, "seed": 7, "n_rows": 2}
    base.update(meta)
    (d / f"{table}.meta.json").write_text(json.dumps(base))
    return d


def test_the_deliverable_table_names_are_unique():
    tables = [d.table for d in DELIVERABLES]
    assert len(tables) == len(set(tables)), "a duplicated table double-counts"


def test_every_command_is_executable_or_an_explicit_not_run():
    for item in DELIVERABLES:
        assert item.command.startswith("python -m src.") or item.command == "NOT RUN"
        if item.command == "NOT RUN":
            assert item.note, f"{item.table}: a NOT RUN deliverable must say why"


def test_a_present_deliverable_carries_relative_provenance(tmp_path):
    results_dir = tmp_path / "results"
    present = DELIVERABLES[0].table
    _write_result(results_dir, "2026-01-01_aaaaaaa", present)
    manifest = build_manifest(results_dir)
    row = manifest[manifest.table == present].iloc[0]
    assert row["status"] == "present"
    assert row["table_committed"]
    assert row["git_sha"] == "abc1234"
    assert row["seed"] == 7
    # Repo-relative: no absolute worktree path, so a fresh checkout resolves it.
    assert row["path"] == f"results/2026-01-01_aaaaaaa/{present}.parquet"
    assert not str(row["path"]).startswith("/")


def test_an_absent_deliverable_is_recorded_not_dropped(tmp_path):
    results_dir = tmp_path / "results"
    results_dir.mkdir()
    manifest = build_manifest(results_dir)
    assert len(manifest) == len(DELIVERABLES)
    assert set(manifest["status"]) == {"absent", "blocked"}
    unavailable = unavailable_deliverables(manifest)
    assert len(unavailable) == len(DELIVERABLES)


def test_the_blinded_challenge_is_blocked_even_with_its_table_committed(tmp_path):
    """The forcing input for the third state.

    The file is committed, so a boolean would read True -- but the deliverable
    is not done. status must be 'blocked', and table_committed must stay True so
    a reader can see both facts at once.
    """
    results_dir = tmp_path / "results"
    _write_result(results_dir, "2026-01-01_aaaaaaa", "blinded_guard_challenge")
    manifest = build_manifest(results_dir).set_index("table")
    row = manifest.loc["blinded_guard_challenge"]
    assert row["status"] == "blocked"
    assert row["table_committed"]
    assert row["path"] is None or row["path"].startswith("results/")


def test_guard_challenge_results_is_blocked_and_not_committed(tmp_path):
    results_dir = tmp_path / "results"
    results_dir.mkdir()
    manifest = build_manifest(results_dir).set_index("table")
    row = manifest.loc["guard_challenge_results"]
    assert row["status"] == "blocked"
    assert not row["table_committed"]


def test_the_committed_manifest_is_current():
    """The sequencing note, made a check.

    The producer was fixed to emit a three-state ``status`` and repo-relative
    paths, but the committed parquet is regenerated by hand after a commit. If
    that step is skipped, Results §6 describes a status column the committed
    table does not have and a teammate's checkout records absolute paths that
    resolve for nobody. This fails the suite instead of shipping the mismatch.

    Regenerate with:
        python -m src.reference.jobs.reproduction_manifest
    on a clean tree, then commit the new ``results/`` directory.
    """
    path = newest_by_time(RESULTS_DIR, "reproduction_manifest")
    assert path is not None, "no committed reproduction_manifest"
    manifest = pd.read_parquet(path)

    assert "status" in manifest.columns, (
        f"{path} predates the three-state status column; regenerate it"
    )
    assert "present" not in manifest.columns
    assert manifest["status"].isin({"present", "blocked", "absent"}).all()

    paths = manifest["path"].dropna()
    absolute = paths[paths.str.startswith("/")]
    assert absolute.empty, (
        f"committed manifest records absolute worktree paths: {absolute.tolist()}"
    )

    # The submission gate must be visible in the artifact, not only in prose.
    blocked = set(manifest.loc[manifest["status"] == "blocked", "table"])
    assert {"blinded_guard_challenge", "guard_challenge_results"} <= blocked
